expname: neus_fangzhou_vangogh

# device_ids: [0]     # single gpu           ; run on specified GPU
# device_ids: [1, 0]  # DP                   ; run on specified GPU
device_ids: -1     # single GPU / DP / DDP; run on all available GPUs; 

data:
  batch_size: 1       # one batch, one image
  data_dir: ./data/fangzhou_nature
  cam_file: 'cameras_sphere.npz'
  downscale: 2        # downscale image for training
  pin_memory: True

  N_rays: 2048       # N_rays for training
  val_rayschunk: 512 # N_rays for validation
  val_downscale: 2    # downscale image for validation

model:
  framework: NeuS
  obj_bounding_radius: 1.0

  variance_init: 0.05
  # N_outside: 32       # number of outside NeRF++ points

  # variance_init: 0.05

  # upsampling related
  upsample_algo:    official_solution   # [direct_use, direct_more, official_solution]
  N_nograd_samples: 2048  # config for upsampling using 'direct_more'
  N_upsample_iters: 4     # config for upsampling using 'official_solution'

  surface:
    D: 8
    W: 256
    skips: [4]
    radius_init: 0.5
    embed_multires: 6

  radiance:
    D: 4
    W: 256
    skips: []
    embed_multires: -1
    embed_multires_view: 4  # as in the NeuS official implementaion

training:
  lr: 5.0e-4
  speed_factor: 10.0    # NOTE: unexpectedly, this is very important. setting to 1.0 will cause some of the DTU instances can not converge correctly.

  # neus
  with_mask: True
  w_eikonal: 0.1
  w_mask: 0.0 #use the 0.0 for unmask as original repo

  log_root_dir: "logs"

  # lr decay, 
  #! set the same as volsdf
  scheduler:
    type: exponential_step
    min_factor: 0.5

  # num_epochs: 50000
  num_iters: 400 # 300k

  ckpt_file: null # will be read by python as None
  ckpt_ignore_keys: []     # only change if you want to drop certain keys in the saved checkpionts.
  ckpt_only_use_keys: null # only change if you want to only use certain keys in the saved checkpionts.

  monitoring: tensorboard

  i_save: 1000       # unit: seconds
  i_backup: 50000   # unit: itertation steps

  i_val: 500
  i_val_mesh: 10000
  is_finetune: True

finetune:
  num_iters: 400
  i_save: 1000       # unit: seconds
  i_backup: 60   # unit: itertation steps
  i_val: 20
  i_val_mesh: 60

  use_eikonal: True
  pretrain_weight: "/home/wangcan/ruixiang/neurecon/logs/neus_fangzhou_masked_2/ckpts/00150000.pt"
  src_text: "photo"
  target_text: "painting, oil on canvas, Vincent van gogh self-portrait style"
  w_perceptual: 1.1
  w_contrastive: 0.2
  w_patchnce: 0.1
  w_clip: 1.0
  w_eikonal: 0.1